services:

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  producer:
    build: .
    container_name: producer-container

    ports:
      - "3000:3000"

    depends_on:
      - redis

    env_file:
      - .env

  worker:
    build: .
    container_name: worker-container

    command: npm run worker

    depends_on:
      - redis

    env_file:
      - .env